### ISSUE TITLE
couldn't execute Build-AzureADAppConsentGrantReport

### ISSUE THREAD

**Issue by sivabalaguru** [microsoft/AzureADToolkit#2]
I am not able to execute Build-AzureADAppConsentGrantReport cmdlet although I have the permission scope Application.ReadWrite.All.

![image](https://user-images.githubusercontent.com/15766653/128457024-3fd2b583-9565-4efb-a534-375e7d6c2d4b.png)

As the error message says it would just need Application.Read.All, But I do have Application.ReadWrite.All in the scope.

Am I missing any other permissions?

**Comment by hoodat** [comment]
Open the script below;

C:\Program Files\WindowsPowerShell\Modules\AzureADToolkit\1.0.796405\Build-AzureADAppConsentGrantReport.ps1

On line 54 add "Application.ReadWrite.All" $apiPermissionScopes to the array. 

It should run after that. I will see about creating a pull request to get this fixed.

**Comment by sivabalaguru** [comment]
Thank you for fixing this.
